### ISSUE TITLE
Login Redirects to Logout Page Immediately on Mosaic Platform (Indic Language Training)

### ISSUE THREAD

**Issue by GuptaSandhali** [fixie-ai/ultravox#289]
After logging into the Mosaic platform, instead of being redirected to the dashboard or home page, I am immediately redirected to the logout page. I am trying to train on Indic languages, but I am unable to proceed due to this issue.

**Comment by zqhuang211** [comment]
This issue is best addressed with the Mosaic platform. We are currently training a new model with significantly expanded coverage for Indic languages. If you have specific public Indic language training datasets in mind, we would be happy to consider including them in the training process.

**Comment by GuptaSandhali** [comment]
Thank you for your response! I appreciate the update on the Indic language training.

However, I am still facing the issue where I am redirected to the logout page immediately after logging in. I have been using the Common Voice dataset for my training, but this issue is preventing me from proceeding further.

Could you please guide me on how to resolve this issue? Are there any specific steps I should take to troubleshoot it?

**Comment by zqhuang211** [comment]
We set up API keys for the Mosaic Platform at console.mosaicml.com and use their command-line interface tool `mcli` to interact with the platform (https://docs.mosaicml.com/projects/mcli/en/latest/ for details). You can reach out to the Mosaic team directly for support on using their platform.

Note that the v0.5 models are already trained on common voice. The amount of Indic language training data is pretty limited on common voice, so the performance can be very limited.

**Comment by GuptaSandhali** [comment]
Thank you for the information! I appreciate the details on the Mosaic platform and the v0.5 models being trained on the Common Voice dataset.
Considering that the performance on Indic languages might be limited with the current dataset, I was wondering if there are any alternative platforms I could explore for training. Would platforms like AWS or others be suitable for training with larger Indic language datasets, or do you have any recommendations?

**Comment by zqhuang211** [comment]
You can choose any of your preferred GPU providers for training/finetuning ultravox models. Besides Mosaic, we were also able to train models on SF compute (https://sfcompute.com). Our upcoming model will have significantly improved performance on Hindi, and we plan to explain coverage to other Indic languages. If you have any specific language in mind, please let us know.
